### ISSUE TITLE
Les descripteurs n'apparaissent pas dans la table

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/dictionary-editor#7]
Par exemple dans : http://dictionary-dev.ieml.io/#/dicEdit/IEML/E:O:.M:O:.-

**Comment by plevyieml** [comment]
![screenshot 2016-07-12 16 45 48](https://cloud.githubusercontent.com/assets/19435943/16783359/a759240e-4851-11e6-8010-d1f3c24ae8cc.png)

**Comment by hadware** [comment]
http://dictionary-dev.ieml.io/#/dicEdit/IEML/E%253AO%253A.M%253AO%253A.-

Je peux avoir un screen de ce lien chez vous? Chez moi les descripteur aparaissent.

**Comment by plevyieml** [comment]
@hadware je ne comprends pas ce que tu demandes. J'ai déjà mis une capture d'écran...

**Comment by hadware** [comment]
Hum oui ça marche 1/2 fois en fiat, c'est étrange, je suis entrain de trouver une piste.

**Comment by hadware** [comment]
Ok il semblerai que le beug ne se passe que si l'on charge directement le terme sans passer par le listing "allIeml". C'est un bug hérité du code de l'ancien dictionnaire (il en est de même si on tente la même chose sur l'ancien dictionnaire : http://dictionary.editor-ie.ml/material#/dicEdit/IEML/M%253A.I%253A.n.- ).
